{{- if .Values.rpaas.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: rpaas-pods
  labels:
{{ include "tsuru-monitoring.labels" . | indent 4 }}
{{- if .Values.tsuruRules.labels }}
{{ toYaml .Values.tsuruRules.labels | indent 4 }}
{{- end }}
{{- if .Values.tsuruRules.annotations }}
  annotations:
{{ toYaml .Values.tsuruRules.annotations | indent 4 }}
{{- end }}
spec:
  endpoints:
    - scheme: http
      relabelings:
        - sourceLabels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
          action: replace
          targetLabel: __metrics_path__
        - sourceLabels: [__meta_kubernetes_pod_container_port_name]
          action: keep
          regex: '.*-metrics'
        - sourceLabels: [__meta_kubernetes_pod_label_rpaas_extensions_tsuru_io_service_name]
          separator: ;
          regex: (.*)
          targetLabel: service
          replacement: $1
          action: replace
        - sourceLabels: [__meta_kubernetes_pod_label_rpaas_extensions_tsuru_io_instance_name]
          separator: ;
          regex: (.*)
          targetLabel: service_instance
          replacement: $1
          action: replace
        - sourceLabels: [__meta_kubernetes_pod_label_rpaas_extensions_tsuru_io_team_owner]
          separator: ;
          regex: (.*)
          targetLabel: service_owner
          replacement: $1
          action: replace
        - sourceLabels: [__meta_kubernetes_pod_label_rpaas_extensions_tsuru_io_cluster_name]
          separator: ;
          regex: (.*)
          targetLabel: service_cluster
          replacement: $1
          action: replace
        - sourceLabels: [__meta_kubernetes_pod_name]
          separator: ;
          regex: (.*)
          targetLabel: kubernetes_pod_name
          replacement: $1
          action: replace
        - sourceLabels: [__meta_kubernetes_pod_container_name]
          separator: ;
          regex: (.*)
          targetLabel: kubernetes_container_name
          replacement: $1
          action: replace
        - sourceLabels: [__meta_kubernetes_pod_node_name]
          separator: ;
          regex: (.*)
          targetLabel: kubernetes_node
          replacement: $1
          action: replace
  namespaceSelector:
{{- toYaml .Values.rpaas.namespaceSelector | nindent 4}}
  selector:
{{- toYaml .Values.rpaas.selector | nindent 4}}
{{- end }}